import logging
import pprint
import yaml
import urllib.parse
import pathlib

class FabModule():
    """
    Definition of a generic Fab module
    """
    def __init__(self, source, **kwargs):
        self.source = source
        self.name = self.source
        for k in kwargs:
            setattr(self, k, kwargs[k])
        self.definition = {}
        self._read()
        logging.debug("Read definition for module: {}".format(self.definition))
        if not self._validate():
            logging.error('Definition YAML for {} is not valid.'.format(self.source))
            raise Exception("YAML is not valid")

    def __str__(self):
        return(pprint.pformat(self.definition, indent=4))
    
    def _read(self):
        parsed_source = urllib.parse.urlparse(self.source)
        logging.debug('Decoded source: {}'.format(parsed_source))
        if parsed_source.scheme == '' or parsed_source.scheme == 'file':
            try:
                f = open(parsed_source.path, 'r')
            except Exception as err:
                logging.error('Could not open file {}: {}'.format(parsed_source.path, err))
                raise
            self.definition = yaml.load(f, Loader=yaml.Loader)
            f.close()
            self.working_dir = pathlib.Path(parsed_source.path).parents[0]
        else:
            logging.error('Unknown scheme "{}" in {}'.format(parsed_source.scheme, self.source))
            return False
        return True

    def _validate(self):
        is_valid = True
        if not 'metadata' in self.definition:
            logging.warning('No metadata found for module {}. Generating some.'.format(self.source))
            self.definition['metadata'] = {}
            self.definition['metadata']['name'] = self.source
            self.definition['metadata']['description'] = 'Autogenerated metadata'
        else:
            if not 'name' in self.definition['metadata']:
                logging.warning("No name set in module {}'s metadata. Autosetting to {}".format(self.name, self.name))
                self.definition['metadata']['name'] = self.name
            else:
                self.name = self.definition['metadata']['name']
            if not 'description' in self.definition['metadata']:
                logging.warning("No description set in module {}'s metadata. Autosetting".format(self.name))
                self.definition['metadata']['description'] = 'Autogenerated'
        
        if not 'containerfile' in self.definition:
            logging.debug("'containerfile' missing from definition yaml for module {}, using default".format(self.name))
            self.definition['containerfile'] = 'Containerfile'
        elif not isinstance(self.definition['containerfile'], str):
            logging.error("'containerfile' is not a string")
            is_valid = False
        self.containerfile = self.definition['containerfile']

        if 'buildargs' in self.definition:
            if not isinstance(self.definition['buildargs'],list):
                logging.error("'buildargs' is not a list")
                is_vaild = False
        else:
            self.definition['buildargs'] = []

        return(is_valid)
